### ISSUE TITLE
using DebounceQueue to have a more elegant method that avoid calling functions repeatedly

### ISSUE THREAD

**Issue by carlosdelfino** [zixia/rx-queue#2]
Hello, I found your project very good.

I believe in his success and thanks for sharing the code openly.

I tried using DebounceQueue to have a more elegant method that avoid calling functions repeatedly in NativeScript, but it did not work that expected, I read your page on npmjs.com.

Could you give me an example if it is possible to use it for this type of application?

```ts
class Page extends BasePage {

  private connectDebounce: DebounceQueue;
  private heartRateIntervalID: number;
  private lastsplice: number = 0;

  private constructor() {
    super();
    this.connectDebounce = new DebounceQueue(1000);
      this.connectDebounce.subscribe(this.connectDebounced);
  }
   public connectDebounced(arg:EventData){
      // realconnect
   } 

// called by user action on NativeScript Page.
  public connect(arg:EventData){
      this.connectDebounce.next(arg);
   }
}
```
Thank you.

**Comment by zixia** [comment]
Thanks for using RxQueue!

Could you please clarify what is your expected and what is not your expected behavior of the RxQueue?

For example, could you please provide a unit test that would fail(or pass) to demonstrate your scenario?

**Comment by carlosdelfino** [comment]
thanks for the quick response.

in the case above, just hoped that by calling the "connect" function more than once in a time less than 1sec it would debounce and call the "connectDebounced" function but it does not make the call under any hypothesis. of the connectDebounced function.

Nor does it issue any exceptions.

**Comment by carlosdelfino** [comment]
I found the problem, was directly passing the function of the class, create an anonymous function to wrap the call of the function instance of the class and now is working as accurate.


```
class Page extends BasePage {

  private connectDebounce: DebounceQueue<EventData>;

  private constructor() {
    super();
    this.connectDebounce = new DebounceQueue<EventData>(1000);
     this.connectDebounce.subscribe((args:EventData)=>this.connectDebounced(args));
  }
   public connectDebounced(arg:EventData){
      // realconnect
   } 

  // called by user action on NativeScript Page.
  public connect(arg:EventData){
      this.connectDebounce.next(arg);
   }
}


```

**Comment by carlosdelfino** [comment]
Thanks.
